// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Point {
    pub x: i32,
    pub y: i32,
}
impl ::core::fmt::Debug for Point {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Point").field("x", &self.x).field("y", &self.y).finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_echo_point_cabi<T: Guest>(arg0: i32, arg1: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::echo_point(Point { x: arg0, y: arg1 });
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Point { x: x2, y: y2 } = result0;
    *ptr1.add(0).cast::<i32>() = _rt::as_i32(x2);
    *ptr1.add(4).cast::<i32>() = _rt::as_i32(y2);
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_echo_tuple_cabi<T: Guest>(arg0: i32, arg1: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::echo_tuple((arg0, arg1));
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let (t2_0, t2_1) = result0;
    *ptr1.add(0).cast::<i32>() = _rt::as_i32(t2_0);
    *ptr1.add(4).cast::<i32>() = _rt::as_i32(t2_1);
    ptr1
}
pub trait Guest {
    fn echo_point(p: Point) -> Point;
    fn echo_tuple(t: (i32, i32)) -> (i32, i32);
}
#[doc(hidden)]
macro_rules! __export_world_marshal_matrix_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "echo-point")] unsafe extern "C" fn
        export_echo_point(arg0 : i32, arg1 : i32,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_echo_point_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "echo-tuple")] unsafe extern "C" fn export_echo_tuple(arg0 : i32,
        arg1 : i32,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_echo_tuple_cabi::<$ty > (arg0, arg1) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_marshal_matrix_cabi;
#[repr(align(4))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 8]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 8]);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_marshal_matrix_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_marshal_matrix_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_marshal_matrix_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:pg-wasm:marshal-matrix:marshal-matrix:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 251] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07w\x01A\x02\x01A\x07\x01\
r\x02\x01xz\x01yz\x03\0\x05point\x03\0\0\x01@\x01\x01p\x01\0\x01\x04\0\x0aecho-p\
oint\x01\x02\x01o\x02zz\x01@\x01\x01t\x03\0\x03\x04\0\x0aecho-tuple\x01\x04\x04\0\
%pg-wasm:marshal-matrix/marshal-matrix\x04\0\x0b\x14\x01\0\x0emarshal-matrix\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-\
bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
